# Generated by Django 6.0.3 on 2026-05-07 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('block', models.CharField(max_length=10)),
                ('floor', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=10)),
                ('gender_type', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll_number', models.IntegerField(unique=True)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ALLOCATED', 'ALLOCATED'), ('VACANT', 'VACANT')], default='ALLOCATED', max_length=10)),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('vacated_date', models.DateField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocation.student')),
            ],
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=10)),
                ('requested_date', models.DateField(auto_now_add=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allocation.student')),
            ],
            options={
                'ordering': ['priority', 'requested_date'],
            },
        ),
    ]
